In [24]:
import numpy as np
import pandas as pd

In [25]:
# zajem strani

url = 'https://www.bsi.si/en/statistics/exchange-rates-and-precious-metals-prices/bank-of-slovenia-exchange-rates-ecb-reference-rates'
df = pd.read_html(url)[0]
df

               Country            Currency Label  Code         Rate
0        United States           US DOLLAR   USD   840      1.09230
1                Japan                 YEN   JPY   392    135.30000
2             Bulgaria       BULGARIAN LEV   BGN   975      1.95580
3       Czech Republic        CZECH KORUNA   CZK   203     24.44100
4              Denmark        DANISH KRONE   DKK   208      7.43780
5       United Kingdom      POUND STERLING   GBP   826      0.83473
6              Hungary              FORINT   HUF   348    377.77000
7               Poland               ZLOTY   PLN   985      4.63280
8              Romania        ROMANIAN LEU   RON   946      4.94330
9               Sweden       SWEDISH KRONA   SEK   752     10.28550
10             Iceland     ICELANDIC KRONA   ISK   352    141.40000
11         Switzerland         SWISS FRANC   CHF   756      1.01870
12              Norway     NORWEGIAN KRONE   NOK   578      9.55230
13             Croatia       CROATIAN KUNA   HRK   191      7.54700
14              Turkey        TURKISH LIRA   TRY   949     16.09980
15           Australia   AUSTRALIAN DOLLAR   AUD    36      1.44310
16              Brazil      BRAZILIAN REAL   BRL   986      5.09960
17              Canada     CANADIAN DOLLAR   CAD   124      1.36470
18               China       YUAN RENMINBI   CNY   156      6.94980
19           Hong Kong    HONG KONG DOLLAR   HKD   344      8.56170
20           Indonesia              RUPIAH   IDR   360  15683.36000
21              Israel  NEW ISRAELI SHEQEL   ILS   376      3.51990
22               India        INDIAN RUPEE   INR   356     82.83430
23  Korea, Republic of                 WON   KRW   410   1330.44000
24              Mexico        MEXICAN PESO   MXN   484     21.87590
25            Malaysia   MALAYSIAN RINGGIT   MYR   458      4.60400
26         New Zealand  NEW ZEALAND DOLLAR   NZD   554      1.57180
27         Philippines     PHILIPPINE PESO   PHP   608     56.16700
28           Singapore    SINGAPORE DOLLAR   SGD   702      1.48440
29            Thailand                BAHT   THB   764     36.70100
30        South Africa                RAND   ZAR   710     15.99340

In [35]:
# zabeležimo vrstni red in vrednosti za eur v array

vrstni_red = df['Currency'].to_numpy()
eur = df['Rate'].to_numpy()

vrstni_red = np.append(vrstni_red, 'EUR')
eur = np.append(eur, 1.00)
eur

array([1.092300e+00, 1.353000e+02, 1.955800e+00, 2.444100e+01,
       7.437800e+00, 8.347300e-01, 3.777700e+02, 4.632800e+00,
       4.943300e+00, 1.028550e+01, 1.414000e+02, 1.018700e+00,
       9.552300e+00, 7.547000e+00, 1.609980e+01, 1.443100e+00,
       5.099600e+00, 1.364700e+00, 6.949800e+00, 8.561700e+00,
       1.568336e+04, 3.519900e+00, 8.283430e+01, 1.330440e+03,
       2.187590e+01, 4.604000e+00, 1.571800e+00, 5.616700e+01,
       1.484400e+00, 3.670100e+01, 1.599340e+01, 1.000000e+00])

In [54]:
# naredimo matriko za Floyd-Warshalla

n = len(eur)
rates = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        rates[i, j] = eur[j] / eur[i]

# krat v plus in max v min
rates = - np.log(rates)
rates

array([[-0.        , -4.81920897, -0.58251375, ..., -3.51451844,
        -2.68389057,  0.08828556],
       [ 4.81920897, -0.        ,  4.23669522, ...,  1.30469053,
         2.1353184 ,  4.90749454],
       [ 0.58251375, -4.23669522, -0.        , ..., -2.93200469,
        -2.10137682,  0.67079932],
       ...,
       [ 3.51451844, -1.30469053,  2.93200469, ..., -0.        ,
         0.83062787,  3.602804  ],
       [ 2.68389057, -2.1353184 ,  2.10137682, ..., -0.83062787,
        -0.        ,  2.77217614],
       [-0.08828556, -4.90749454, -0.67079932, ..., -3.602804  ,
        -2.77217614, -0.        ]])

In [56]:
def floyd_warshall(utezi):
    """
    Izvede Floyd-Warshallov algoritem za graf z danimi utežmi.

    utezi = matrika, ki predstavlja graf
    """
    # naredimo matriko za začetek -> inf matrika
    n = len(utezi)
    dist = np.zeros((n, n))
    dist.fill(np.inf)

    # to je nepotrebno -> samo začni z utezi
    # mogoče bolj splošno
    for i in range(n):
        for j in range(n):
            if i == j:
                dist[i, j] = 0
            elif utezi[i, j] < np.inf:
                dist[i, j] = utezi[i, j]

    # dejanski algo      
    for k in range(n):
        for i in range(n):
            for j in range(n):
                if dist[i, j] > dist[i, k] + dist[k, j]:
                    dist[i, j] = dist[i, k] + dist[k, j]
    
    return dist

In [61]:
optimum = floyd_warshall(rates)
np.diag(optimum)

array([-198655.5118065 , -198655.5118065 , -198655.5118065 ,
       -198655.5118065 , -198655.5118065 , -198655.5118065 ,
       -198655.5118065 , -198655.5118065 , -198655.5118065 ,
       -198655.5118065 , -198655.5118065 , -198655.5118065 ,
       -198655.5118065 , -198655.51180651, -198655.51180652,
       -198655.51180661, -198655.51180714, -198655.51181031,
       -198655.51182932, -198655.51194339, -198655.51262785,
       -198655.5167346 , -198655.54137509, -198655.68921805,
       -198656.57627577, -198661.89862208, -198693.83269998,
       -198885.43716739, -200035.06397183, -206932.82479844,
       -248319.38975813, -496638.77951626])

In [68]:
tes = np.array([[0, np.inf, -2, np.inf], [4, 0, 3, np.inf], [np.inf, np.inf, 0, 2], [np.inf, -1, np.inf, 0]])
print(floyd_warshall(tes))

[[ 0. -1. -2.  0.]
 [ 4.  0.  2.  4.]
 [ 5.  1.  0.  2.]
 [ 3. -1.  1.  0.]]

In [ ]:
#TODO: rekonstrukcija cikla?